### ISSUE TITLE
How to show on frontend

### ISSUE THREAD

**Issue by StuartMorris0** [stuttter/wp-event-calendar#11]
Forgive me for being naive here!

So you download and setup the plugin add a bunch of events etc, but I do not see any documentation/wiki information on how to make these show on the front end.

I am looking to create a view similar to this:
http://rinse.fm/schedule/

Which shows the days then a calender on the right to select different days and view the 'events' as  a schedule in a list format. Is that possible?

Thanks

**Comment by jeremyfelt** [comment]
@StuartMorris0 A bit of custom code is needed to make the events publicly queryable in the plugin's current state. See #3 for some background.

Something along the lines of this would work:

```
add_filter( 'register_post_type_args', function( $args, $name ) {
    if ( 'event' === $name ) {
        $args['publicly_queryable'] = true;
    }

   return $args;
}, 10, 2 );
```

You'd still need to sort out the display of meta, etc.. :)
