### ISSUE TITLE
Bulk/quick edit changes to Types don't save

### ISSUE THREAD

**Issue by philcable** [stuttter/wp-event-calendar#16]
This seems to be due to the `value` attribute being output as the term name rather than ID at https://github.com/stuttter/wp-event-calendar/blob/master/wp-event-calendar/includes/events/metaboxes.php#L59.

**Comment by michaelsavchuk** [comment]
I believe bulk editing is intentionally blocked for some reason?

https://github.com/stuttter/wp-event-calendar/blob/master/wp-event-calendar/includes/events/metaboxes.php#L435
