### ISSUE TITLE
Version 0.2.3 broken because of missing capabilities

### ISSUE THREAD

**Issue by ArchCarrier** [stuttter/wp-event-calendar#4]
As posted on the wordpress.org forum:

> With version 0.2.3 some things were changed in the way capabilities are handled, the map_meta_cap in the register_post_type function was added and set to true
> https://github.com/stuttter/wp-event-calendar/commit/f2c3f1c44bfca130be29c8407f41ee1ab8b7a44f
> 
> This causes the plugin to stop function, since an Administrator cannot create an event anymore. If I remove the map_meta_cap = true or if I use a capabilities plugin like Members and manually map the event capabilities to the role I have, it works again.

**Comment by johnjamesjacoby** [comment]
This should be fixed in 0.3.0.

Please reopen if not, and I'll take another look at what might be going on.
