### ISSUE TITLE
Can't query by event category in admin

### ISSUE THREAD

**Issue by joelworsham** [stuttter/wp-event-calendar#9]
If you go the event category screen in the admin and click on the number for "count", it goes back to the wp posts list table, with the query arg of "event-category", but no events show, even if some do exist. It's because of `wp_event_calendar_maybe_filter_by_fields()`. The issue is that the function adds a tax_query of `term_id`, even though, in this instance (and possibly others), the value of the query arg is the term name, rather than the term id.

**Comment by JJJ** [comment]
This was inadvertently fixed in what will be 1.0.0.

**Comment by joelworsham** [comment]
Perfect! Thanks.
